apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
      name: memcached
  selector:
    app: memcached
