---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: radio-fe-app
spec:
  selector:
    matchLabels:
      app: radio-fe-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: radio-fe-app
    spec:
      containers:
      - name: radio-fe-app
        image: localhost:5000/radio-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: radio
  name: radio-fe-app
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.100
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app: radio-fe-app
---
