---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: radio-fe-app
spec:
  selector:
    matchLabels:
      app: radio-fe-app
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: radio-fe-app
    spec:
      containers:
      - name: radio-fe-app
        image: localhost:5000/radio-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          failureThreshold: 60
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: radio
  name: radio-fe-app
spec:
  type: NodePort
  clusterIP: 10.43.0.240
  ports:
    - protocol: TCP
      name: http
      port: 80
      nodePort: 30404
      targetPort: 80
  selector:
    app: radio-fe-app
---
