---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: icecast-srv
spec:
  selector:
    matchLabels:
      app: icecast-srv
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: icecast-srv
    spec:
      containers:
      - name: icecast-srv
        image: localhost:5000/docker-icecast:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: radio
  name: icecast-srv
spec:
  type: NodePort
  clusterIP: 10.96.0.200
  ports:
    - protocol: TCP
      name: audio-stream
      port: 8000
      nodePort: 30420
      targetPort: 8000
  selector:
    app: icecast-srv
---
